//
// File generated by rootcint at Sun Jun 19 19:41:30 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JunDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JunDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::JunParticle JunParticle;
      #else
      class JunParticle  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~JunParticle() throw() {};
         string name; //
         ::TVector3 direction; //
         double energy; //
         double theta; //
         double phi; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void JunParticle_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void JunParticle_Dictionary();
   static void *new_JunParticle(void *p = 0);
   static void *newArray_JunParticle(Long_t size, void *p);
   static void delete_JunParticle(void *p);
   static void deleteArray_JunParticle(void *p);
   static void destruct_JunParticle(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::JunParticle*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::JunParticle) == sizeof( ::ROOTShadow::Shadow::JunParticle));
      ::JunParticle *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::JunParticle),0);
      static ::ROOT::TGenericClassInfo 
         instance("JunParticle", "/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunParticle.hh", 9,
                  typeid(::JunParticle), ::ROOT::DefineBehavior(ptr, ptr),
                  &JunParticle_ShowMembers, &JunParticle_Dictionary, isa_proxy, 4,
                  sizeof(::JunParticle) );
      instance.SetNew(&new_JunParticle);
      instance.SetNewArray(&newArray_JunParticle);
      instance.SetDelete(&delete_JunParticle);
      instance.SetDeleteArray(&deleteArray_JunParticle);
      instance.SetDestructor(&destruct_JunParticle);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::JunParticle*)
   {
      return GenerateInitInstanceLocal((::JunParticle*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JunParticle*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void JunParticle_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::JunParticle*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void JunParticle_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class JunParticle.
      typedef ::ROOTShadow::Shadow::JunParticle ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::JunParticle*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "name", (void*)&sobj->name);
      R__insp.InspectMember("string", (void*)&sobj->name, "name.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "direction", &sobj->direction);
      R__insp.InspectMember(sobj->direction, "direction.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energy", &sobj->energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "theta", &sobj->theta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phi", &sobj->phi);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_JunParticle(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JunParticle : new ::JunParticle;
   }
   static void *newArray_JunParticle(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JunParticle[nElements] : new ::JunParticle[nElements];
   }
   // Wrapper around operator delete
   static void delete_JunParticle(void *p) {
      delete ((::JunParticle*)p);
   }
   static void deleteArray_JunParticle(void *p) {
      delete [] ((::JunParticle*)p);
   }
   static void destruct_JunParticle(void *p) {
      typedef ::JunParticle current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::JunParticle

namespace ROOTDict {
   void vectorlEJunParticlegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEJunParticlegR_Dictionary();
   static void *new_vectorlEJunParticlegR(void *p = 0);
   static void *newArray_vectorlEJunParticlegR(Long_t size, void *p);
   static void delete_vectorlEJunParticlegR(void *p);
   static void deleteArray_vectorlEJunParticlegR(void *p);
   static void destruct_vectorlEJunParticlegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<JunParticle>*)
   {
      vector<JunParticle> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<JunParticle>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<JunParticle>", -2, "prec_stl/vector", 49,
                  typeid(vector<JunParticle>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEJunParticlegR_Dictionary, isa_proxy, 4,
                  sizeof(vector<JunParticle>) );
      instance.SetNew(&new_vectorlEJunParticlegR);
      instance.SetNewArray(&newArray_vectorlEJunParticlegR);
      instance.SetDelete(&delete_vectorlEJunParticlegR);
      instance.SetDeleteArray(&deleteArray_vectorlEJunParticlegR);
      instance.SetDestructor(&destruct_vectorlEJunParticlegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<JunParticle> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<JunParticle>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEJunParticlegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<JunParticle>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEJunParticlegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<JunParticle> : new vector<JunParticle>;
   }
   static void *newArray_vectorlEJunParticlegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<JunParticle>[nElements] : new vector<JunParticle>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEJunParticlegR(void *p) {
      delete ((vector<JunParticle>*)p);
   }
   static void deleteArray_vectorlEJunParticlegR(void *p) {
      delete [] ((vector<JunParticle>*)p);
   }
   static void destruct_vectorlEJunParticlegR(void *p) {
      typedef vector<JunParticle> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<JunParticle>

/********************************************************
* JunDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJunDict();

extern "C" void G__set_cpp_environmentJunDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunDataWriter.hh");
  G__add_compiledheader("/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunDSSDAngle.hh");
  G__add_compiledheader("/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunErrors.hh");
  G__add_compiledheader("/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunLossCorrection.hh");
  G__add_compiledheader("/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunParMan.hh");
  G__add_compiledheader("/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunParticle.hh");
  G__add_compiledheader("/home/fengjun/CodesAtPKU/simu_ciae13c/analysis/include/JunTreeReader.hh");
  G__cpp_reset_tagtableJunDict();
}
#include <new>
extern "C" int G__cpp_dllrevJunDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JunParticle */
static int G__JunDict_583_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunParticle* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle[n];
     } else {
       p = new((void*) gvp) JunParticle[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle;
     } else {
       p = new((void*) gvp) JunParticle;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_583_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JunParticle*) G__getstructoffset())->SetParticle(*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__JunDict_583_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JunParticle* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JunParticle(*(JunParticle*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JunParticle G__TJunParticle;
static int G__JunDict_583_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JunParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JunParticle*) (soff+(sizeof(JunParticle)*i)))->~G__TJunParticle();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JunParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JunParticle*) (soff))->~G__TJunParticle();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__JunDict_583_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunParticle* dest = (JunParticle*) G__getstructoffset();
   *dest = *(JunParticle*) libp->para[0].ref;
   const JunParticle& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* vector<JunParticle,allocator<JunParticle> > */
static int G__JunDict_623_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::reference obj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->at((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::const_reference obj = ((const vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->at((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::iterator* pobj;
         vector<JunParticle,allocator<JunParticle> >::iterator xobj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->begin();
         pobj = new vector<JunParticle,allocator<JunParticle> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::iterator* pobj;
         vector<JunParticle,allocator<JunParticle> >::iterator xobj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->end();
         pobj = new vector<JunParticle,allocator<JunParticle> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::reverse_iterator* pobj;
         vector<JunParticle,allocator<JunParticle> >::reverse_iterator xobj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->rbegin();
         pobj = new vector<JunParticle,allocator<JunParticle> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::reverse_iterator* pobj;
         vector<JunParticle,allocator<JunParticle> >::reverse_iterator xobj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->rend();
         pobj = new vector<JunParticle,allocator<JunParticle> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->max_size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->resize((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->resize((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]), *((JunParticle*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->capacity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->empty());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::reference obj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->operator[]((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::const_reference obj = ((const vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->operator[]((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<JunParticle,allocator<JunParticle> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<JunParticle,allocator<JunParticle> >[n];
     } else {
       p = new((void*) gvp) vector<JunParticle,allocator<JunParticle> >[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<JunParticle,allocator<JunParticle> >;
     } else {
       p = new((void*) gvp) vector<JunParticle,allocator<JunParticle> >;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<JunParticle,allocator<JunParticle> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<JunParticle,allocator<JunParticle> >((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]), *(JunParticle*) libp->para[1].ref);
     } else {
       p = new((void*) gvp) vector<JunParticle,allocator<JunParticle> >((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]), *(JunParticle*) libp->para[1].ref);
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<JunParticle,allocator<JunParticle> >((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) vector<JunParticle,allocator<JunParticle> >((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<JunParticle,allocator<JunParticle> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<JunParticle,allocator<JunParticle> >(*(vector<JunParticle,allocator<JunParticle> >*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) vector<JunParticle,allocator<JunParticle> >(*(vector<JunParticle,allocator<JunParticle> >*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<JunParticle,allocator<JunParticle> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<JunParticle,allocator<JunParticle> >(*((vector<JunParticle,allocator<JunParticle> >::const_iterator*) G__int(libp->para[0])), *((vector<JunParticle,allocator<JunParticle> >::const_iterator*) G__int(libp->para[1])));
   } else {
     p = new((void*) gvp) vector<JunParticle,allocator<JunParticle> >(*((vector<JunParticle,allocator<JunParticle> >::const_iterator*) G__int(libp->para[0])), *((vector<JunParticle,allocator<JunParticle> >::const_iterator*) G__int(libp->para[1])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<JunParticle,allocator<JunParticle> >& obj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->operator=(*(vector<JunParticle,allocator<JunParticle> >*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->reserve((vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JunParticle& obj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->front();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JunParticle& obj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->back();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->push_back(*(JunParticle*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->swap(*(vector<JunParticle,allocator<JunParticle> >*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<JunParticle,allocator<JunParticle> >::iterator* pobj;
         vector<JunParticle,allocator<JunParticle> >::iterator xobj = ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->insert(*((vector<JunParticle,allocator<JunParticle> >::iterator*) G__int(libp->para[0])), *(JunParticle*) libp->para[1].ref);
         pobj = new vector<JunParticle,allocator<JunParticle> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->insert(*((vector<JunParticle,allocator<JunParticle> >::iterator*) G__int(libp->para[0])), *((vector<JunParticle,allocator<JunParticle> >::const_iterator*) G__int(libp->para[1]))
, *((vector<JunParticle,allocator<JunParticle> >::const_iterator*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->insert(*((vector<JunParticle,allocator<JunParticle> >::iterator*) G__int(libp->para[0])), (vector<JunParticle,allocator<JunParticle> >::size_type) G__int(libp->para[1])
, *(JunParticle*) libp->para[2].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->pop_back();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->erase(*((vector<JunParticle,allocator<JunParticle> >::iterator*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->erase(*((vector<JunParticle,allocator<JunParticle> >::iterator*) G__int(libp->para[0])), *((vector<JunParticle,allocator<JunParticle> >::iterator*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_623_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<JunParticle,allocator<JunParticle> >*) G__getstructoffset())->clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vector<JunParticle,allocator<JunParticle> > G__TvectorlEJunParticlecOallocatorlEJunParticlegRsPgR;
static int G__JunDict_623_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vector<JunParticle,allocator<JunParticle> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vector<JunParticle,allocator<JunParticle> >*) (soff+(sizeof(vector<JunParticle,allocator<JunParticle> >)*i)))->~G__TvectorlEJunParticlecOallocatorlEJunParticlegRsPgR();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vector<JunParticle,allocator<JunParticle> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vector<JunParticle,allocator<JunParticle> >*) (soff))->~G__TvectorlEJunParticlecOallocatorlEJunParticlegRsPgR();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JunParticle */

/* vector<JunParticle,allocator<JunParticle> > */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJunDict {
 public:
  G__Sizep2memfuncJunDict(): p(&G__Sizep2memfuncJunDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJunDict::*p)();
};

size_t G__get_sizep2memfuncJunDict()
{
  G__Sizep2memfuncJunDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJunDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJunDict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__JunDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Par_DSSD>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TSpline2*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TMVA::TSpline2*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TMVA::TSpline2*,less<string> >",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JunParticle>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("value_type",117,G__get_linked_tagnum(&G__JunDictLN_JunParticle),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pointer",85,G__get_linked_tagnum(&G__JunDictLN_JunParticle),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__JunDictLN_JunParticle),256,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reference",117,G__get_linked_tagnum(&G__JunDictLN_JunParticle),1,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reference",117,G__get_linked_tagnum(&G__JunDictLN_JunParticle),257,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JunParticle */
static void G__setup_memvarJunParticle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   { JunParticle *p; p=(JunParticle*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->name)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__JunDictLN_string),-1,-1,1,"name=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->direction)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__JunDictLN_TVector3),-1,-1,1,"direction=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->energy)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"energy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->theta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"theta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->phi)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"phi=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* vector<JunParticle,allocator<JunParticle> > */
static void G__setup_memvarvectorlEJunParticlecOallocatorlEJunParticlegRsPgR(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   { vector<JunParticle,allocator<JunParticle> > *p; p=(vector<JunParticle,allocator<JunParticle> >*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJunDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJunParticle(void) {
   /* JunParticle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   G__memfunc_setup("JunParticle",1121,G__JunDict_583_0_1, 105, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetParticle",1120,G__JunDict_583_0_2, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - pName d - 'Double_t' 0 - pEnergy "
"u 'TVector3' - 0 - pDirection", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("JunParticle", 1121, G__JunDict_583_0_3, (int) ('i'), G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 1, 1, 1, 0, "u 'JunParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JunParticle", 1247, G__JunDict_583_0_4, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__JunDict_583_0_5, (int) ('u'), G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 1, 1, 1, 1, 0, "u 'JunParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncvectorlEJunParticlecOallocatorlEJunParticlegRsPgR(void) {
   /* vector<JunParticle,allocator<JunParticle> > */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR));
   G__memfunc_setup("at",213,G__JunDict_623_0_1, 117, G__get_linked_tagnum(&G__JunDictLN_JunParticle), G__defined_typename("vector<JunParticle,allocator<JunParticle> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("at",213,G__JunDict_623_0_2, 117, G__get_linked_tagnum(&G__JunDictLN_JunParticle), G__defined_typename("vector<JunParticle,allocator<JunParticle> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("begin",517,G__JunDict_623_0_3, 117, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("end",311,G__JunDict_623_0_4, 117, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rbegin",631,G__JunDict_623_0_5, 117, G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR), G__defined_typename("vector<JunParticle,allocator<JunParticle> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rend",425,G__JunDict_623_0_6, 117, G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR), G__defined_typename("vector<JunParticle,allocator<JunParticle> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__JunDict_623_0_7, 107, -1, G__defined_typename("vector<JunParticle,allocator<JunParticle> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("max_size",864,G__JunDict_623_0_8, 107, -1, G__defined_typename("vector<JunParticle,allocator<JunParticle> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__JunDict_623_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__JunDict_623_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - sz u 'JunParticle' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("capacity",846,G__JunDict_623_0_11, 107, -1, G__defined_typename("vector<JunParticle,allocator<JunParticle> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("empty",559,G__JunDict_623_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__JunDict_623_0_13, 117, G__get_linked_tagnum(&G__JunDictLN_JunParticle), G__defined_typename("vector<JunParticle,allocator<JunParticle> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__JunDict_623_0_14, 117, G__get_linked_tagnum(&G__JunDictLN_JunParticle), G__defined_typename("vector<JunParticle,allocator<JunParticle> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<JunParticle,allocator<JunParticle> >",4182,G__JunDict_623_0_15, 105, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<JunParticle,allocator<JunParticle> >",4182,G__JunDict_623_0_16, 105, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR), -1, 0, 2, 1, 1, 0, 
"k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - n u 'JunParticle' - 11 'JunParticle()' value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<JunParticle,allocator<JunParticle> >",4182,G__JunDict_623_0_17, 105, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<JunParticle,allocator<JunParticle> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<JunParticle,allocator<JunParticle> >",4182,G__JunDict_623_0_18, 105, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR), -1, 0, 2, 1, 1, 0, 
"u 'vector<JunParticle,allocator<JunParticle> >::iterator' 'vector<JunParticle,allocator<JunParticle> >::const_iterator' 10 - first u 'vector<JunParticle,allocator<JunParticle> >::iterator' 'vector<JunParticle,allocator<JunParticle> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__JunDict_623_0_19, 117, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<JunParticle,allocator<JunParticle> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("reserve",764,G__JunDict_623_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("front",553,G__JunDict_623_0_21, 117, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("back",401,G__JunDict_623_0_22, 117, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("push_back",944,G__JunDict_623_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'JunParticle' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("swap",443,G__JunDict_623_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JunParticle,allocator<JunParticle> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__JunDict_623_0_25, 117, G__get_linked_tagnum(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0, 
"u 'vector<JunParticle,allocator<JunParticle> >::iterator' - 0 - position u 'JunParticle' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__JunDict_623_0_26, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<JunParticle,allocator<JunParticle> >::iterator' - 0 - position u 'vector<JunParticle,allocator<JunParticle> >::iterator' 'vector<JunParticle,allocator<JunParticle> >::const_iterator' 10 - first "
"u 'vector<JunParticle,allocator<JunParticle> >::iterator' 'vector<JunParticle,allocator<JunParticle> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__JunDict_623_0_27, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<JunParticle,allocator<JunParticle> >::iterator' - 0 - position k - 'vector<JunParticle,allocator<JunParticle> >::size_type' 0 - n "
"u 'JunParticle' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("pop_back",831,G__JunDict_623_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__JunDict_623_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JunParticle,allocator<JunParticle> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__JunDict_623_0_30, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<JunParticle,allocator<JunParticle> >::iterator' - 0 - first u 'vector<JunParticle,allocator<JunParticle> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clear",519,G__JunDict_623_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vector<JunParticle,allocator<JunParticle> >", 4308, G__JunDict_623_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJunDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJunDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJunDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JunDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__JunDictLN_JunParticle = { "JunParticle" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR = { "vector<Par_DSSD,allocator<Par_DSSD> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Par_DSSD,allocator<Par_DSSD> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR = { "map<string,TMVA::TSpline2*,less<string>,allocator<pair<const string,TMVA::TSpline2*> > >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR = { "vector<JunParticle,allocator<JunParticle> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator = { "vector<JunParticle,allocator<JunParticle> >::iterator" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JunParticle,allocator<JunParticle> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJunDict() {
  G__JunDictLN_string.tagnum = -1 ;
  G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__JunDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__JunDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__JunDictLN_TVector3.tagnum = -1 ;
  G__JunDictLN_JunParticle.tagnum = -1 ;
  G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR.tagnum = -1 ;
  G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR.tagnum = -1 ;
  G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJunDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JunDictLN_string);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JunDictLN_JunParticle),sizeof(JunParticle),-1,263424,(char*)NULL,G__setup_memvarJunParticle,G__setup_memfuncJunParticle);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR),sizeof(vector<JunParticle,allocator<JunParticle> >),-1,298752,(char*)NULL,G__setup_memvarvectorlEJunParticlecOallocatorlEJunParticlegRsPgR,G__setup_memfuncvectorlEJunParticlecOallocatorlEJunParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupJunDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJunDict()");
  G__set_cpp_environmentJunDict();
  G__cpp_setup_tagtableJunDict();

  G__cpp_setup_inheritanceJunDict();

  G__cpp_setup_typetableJunDict();

  G__cpp_setup_memvarJunDict();

  G__cpp_setup_memfuncJunDict();
  G__cpp_setup_globalJunDict();
  G__cpp_setup_funcJunDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJunDict();
  return;
}
class G__cpp_setup_initJunDict {
  public:
    G__cpp_setup_initJunDict() { G__add_setup_func("JunDict",(G__incsetup)(&G__cpp_setupJunDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJunDict() { G__remove_setup_func("JunDict"); }
};
G__cpp_setup_initJunDict G__cpp_setup_initializerJunDict;

