/********************************************************************
* JunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJunDict();
extern void G__cpp_setup_inheritanceJunDict();
extern void G__cpp_setup_typetableJunDict();
extern void G__cpp_setup_memvarJunDict();
extern void G__cpp_setup_globalJunDict();
extern void G__cpp_setup_memfuncJunDict();
extern void G__cpp_setup_funcJunDict();
extern void G__set_cpp_environmentJunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/fengjun/TestCode/13C_simulation/analysis/include/JunDataWriter.hh"
#include "/home/fengjun/TestCode/13C_simulation/analysis/include/JunDSSDAngle.hh"
#include "/home/fengjun/TestCode/13C_simulation/analysis/include/JunParMan.hh"
#include "/home/fengjun/TestCode/13C_simulation/analysis/include/JunParticle.hh"
#include "/home/fengjun/TestCode/13C_simulation/analysis/include/JunTreeReader.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JunDictLN_string;
extern G__linked_taginfo G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__JunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__JunDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__JunDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__JunDictLN_TVector3;
extern G__linked_taginfo G__JunDictLN_JunParticle;
extern G__linked_taginfo G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgR;
extern G__linked_taginfo G__JunDictLN_vectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiterator;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEJunParticlecOallocatorlEJunParticlegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<JunParticle,allocator<JunParticle> > G__vectorlEJunParticlecOallocatorlEJunParticlegRsPgR;
